project_id = "pkkcaknnktqevvlydjna"

[functions.ai-map-columns]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.get-user-stats]
verify_jwt = true

[functions.list-users]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false